language: python

sudo: false

notifications:
  email: false

python: "3.5"

install:
  - git clone https://github.com/evhub/coconut.git
  - pip install ./coconut
  - git clone https://github.com/evhub/tmtools.git
  - pip install ./tmtools

script:
  - coconut -s . --recursionlimit 1500
  - python build.py
